//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaiVietSmileTravel.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThaiVietSmileTravel.Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่มสินค้า.
        /// </summary>
        public static string btnAddShoping {
            get {
                return ResourceManager.GetString("btnAddShoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ซื้อสินค้าต่อ.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียด.
        /// </summary>
        public static string btnDetail {
            get {
                return ResourceManager.GetString("btnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จองทัวร์.
        /// </summary>
        public static string btnOrderTour {
            get {
                return ResourceManager.GetString("btnOrderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่ง.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวนคน.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษาอังกฤษ.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติดต่อเรา.
        /// </summary>
        public static string h3Contact {
            get {
                return ResourceManager.GetString("h3Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่อยู่.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันที่อยู่ติดต่อจากเว็บไซต์ thaivietsmile.
        /// </summary>
        public static string lblConfigFromEmailDisplayNameContact {
            get {
                return ResourceManager.GetString("lblConfigFromEmailDisplayNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การยืนยันการจองจากเว็บไซต์ thaivietsmile.
        /// </summary>
        public static string lblConfigFromEmailDisplayNameOder {
            get {
                return ResourceManager.GetString("lblConfigFromEmailDisplayNameOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการสั่งซื้อ thaivietsmile เว็บไซต์.
        /// </summary>
        public static string lblConfigOderTour {
            get {
                return ResourceManager.GetString("lblConfigOderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณอยากได้ข้อมูลเพิ่มเติม.
        /// </summary>
        public static string lblContactQuestion {
            get {
                return ResourceManager.GetString("lblContactQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&quot;color:green&quot;&gt;THAIVIET SMILE TRAVEL CO., LTD.&lt;/h4&gt;
        ///                &lt;ul&gt;
        ///					&lt;li&gt; รับทำแลนด์ทัวร์เวียดนาม เชียวชาญทุกเส้นทางในเวียดนาม&lt;/li&gt;
        ///					&lt;li&gt;รับทำแลนด์ทัวร์ เวียดนามเหนือ - เวียดนามกลาง - เวียดนามใต้ &lt;/li&gt;
        ///					&lt;li&gt;บริการจัดกรุ๊ปดูงาน กรุ๊ปสัมมา (ทางบริษัทยินดีติดต่อประสานงานหน่วยงานในประเทศเวียดนามให้ได้ โดยไม่เสียค่าใช้จ่าย)&lt;/li&gt;
        ///					&lt;li&gt;มีไกด์นำเที่ยว พูดภาษาไทย อังกฤษ มารญาติดี ดูแลเอาใจใส่ลูกค้า&lt;/li&gt;
        ///                    &lt;li&gt;ติดต่อสอบถามได้ที่ Mr.Long เบอร์โทรไทย 0876366396 - เว [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lblContentAbout {
            get {
                return ResourceManager.GetString("lblContentAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เข้าชมเว็บไซต์.
        /// </summary>
        public static string lblCountVisistor {
            get {
                return ResourceManager.GetString("lblCountVisistor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วันที่จอง.
        /// </summary>
        public static string lblDateOrder {
            get {
                return ResourceManager.GetString("lblDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to วัันที่.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to อีเมล์.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การติดต่อกับลูกค้า.
        /// </summary>
        public static string lblFromEmailDisplayNameContact {
            get {
                return ResourceManager.GetString("lblFromEmailDisplayNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยืนยันการติดต่อจากเว็บไซต์ thaivietsmile.
        /// </summary>
        public static string lblFromEmailDisplayNameOder {
            get {
                return ResourceManager.GetString("lblFromEmailDisplayNameOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&quot;color:green&quot;&gt;THAIVIET SMILE TRAVEL CO., LTD.&lt;/h4&gt;
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;ติดต่อสอบถามได้ที่ Mr.Long เบอร์โทรไทย 0876366396 - เวียดนาม 00984 916745457&lt;/li&gt;
        ///                    &lt;li&gt;E-mail : thaivietsmiletravel@gmail.com&lt;/li&gt;
        ///                    &lt;li&gt;Skype : thaivietsmiletravel&lt;/li&gt;
        ///                    &lt;li&gt;ID Line : thaivietsmiletravel &lt;/li&gt;
        ///                    &lt;li style=&quot;color:green&quot;&gt;สำนักงานที่ ฮานอย&lt;/li&gt;
        ///                    &lt;li&gt;268 Nguyen Xien Str., Thanh Xuan Dist., H [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lblHeadContact {
            get {
                return ResourceManager.GetString("lblHeadContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลการท่องเที่ยว.
        /// </summary>
        public static string lblHederFormOder {
            get {
                return ResourceManager.GetString("lblHederFormOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาพ.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อลูกค้า.
        /// </summary>
        public static string lblNameCustome {
            get {
                return ResourceManager.GetString("lblNameCustome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อลูกค้า.
        /// </summary>
        public static string lblNameCustomOder {
            get {
                return ResourceManager.GetString("lblNameCustomOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ชื่อของการท่องเที่ยว.
        /// </summary>
        public static string lblNameTour {
            get {
                return ResourceManager.GetString("lblNameTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุืน.
        /// </summary>
        public static string lblNight {
            get {
                return ResourceManager.GetString("lblNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ยังไม่ทัวร์ที่ได้จอง - กรุณาเลือกทัวร์.
        /// </summary>
        public static string lblNoSelectTour {
            get {
                return ResourceManager.GetString("lblNoSelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หมายเหตุ เมื่อได้จองทัวร์ คุณไม่ต้องจ่ายออนไลน์ มีพนักงานพวกเราจะติดต่อกลับ.
        /// </summary>
        public static string lblNoteOrderTour {
            get {
                return ResourceManager.GetString("lblNoteOrderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        public static string lblNumberCustom {
            get {
                return ResourceManager.GetString("lblNumberCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รหัสทัวร์.
        /// </summary>
        public static string lblNumberTour {
            get {
                return ResourceManager.GetString("lblNumberTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เบอร์โทร.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ค้นหา.
        /// </summary>
        public static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คำสั่งซื้อใหม่จาก thaivietsmile เว็บไซต์.
        /// </summary>
        public static string lblSubOderTour {
            get {
                return ResourceManager.GetString("lblSubOderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to จำนวน.
        /// </summary>
        public static string lblSumPrice {
            get {
                return ResourceManager.GetString("lblSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลเข้าในฟอร์มข้างล่าง พวกเราจะติดต่อกลับนะคะ.
        /// </summary>
        public static string lblTitleInputFormContact {
            get {
                return ResourceManager.GetString("lblTitleInputFormContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ที่ัวร์.
        /// </summary>
        public static string lblTour {
            get {
                return ResourceManager.GetString("lblTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ข้อมูลรายละเอียด.
        /// </summary>
        public static string lblTourDetail {
            get {
                return ResourceManager.GetString("lblTourDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต่อหน่วย.
        /// </summary>
        public static string lblUnitPrice {
            get {
                return ResourceManager.GetString("lblUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณได้กำหนดให้ประสบความสำเร็จในการท่องเที่ยว เราจะติดต่อคุณ.
        /// </summary>
        public static string oderTourSuccess {
            get {
                return ResourceManager.GetString("oderTourSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่ประสบความสำเร็จในการจอง โปรดรีเซ็ต.
        /// </summary>
        public static string orderTourError {
            get {
                return ResourceManager.GetString("orderTourError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกที่อยู่.
        /// </summary>
        public static string plhAddress {
            get {
                return ResourceManager.GetString("plhAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ดด/วว/ปปปป.
        /// </summary>
        public static string plhDateOrder {
            get {
                return ResourceManager.GetString("plhDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกอีเมล์.
        /// </summary>
        public static string plhEmail {
            get {
                return ResourceManager.GetString("plhEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกที่อยู่.
        /// </summary>
        public static string plhEnterAdress {
            get {
                return ResourceManager.GetString("plhEnterAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอก บริษัท.
        /// </summary>
        public static string plhEnterCompany {
            get {
                return ResourceManager.GetString("plhEnterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกอีเมล.
        /// </summary>
        public static string plhEnterEmail {
            get {
                return ResourceManager.GetString("plhEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อแรก.
        /// </summary>
        public static string plhEnterFirtName {
            get {
                return ResourceManager.GetString("plhEnterFirtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาใส่นามสกุล.
        /// </summary>
        public static string plhEnterLastName {
            get {
                return ResourceManager.GetString("plhEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาใส่ข้อความของคุณที่นี่.
        /// </summary>
        public static string plhEnterMesseage {
            get {
                return ResourceManager.GetString("plhEnterMesseage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณาใส่โทรศัพท์.
        /// </summary>
        public static string plhEnterPhone {
            get {
                return ResourceManager.GetString("plhEnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกครบ ชื่อ นามสกุล.
        /// </summary>
        public static string plhNameCustome {
            get {
                return ResourceManager.GetString("plhNameCustome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เขียนหมายเหตุ ถ้ามี.
        /// </summary>
        public static string plhNote {
            get {
                return ResourceManager.GetString("plhNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกเบอร์โทร.
        /// </summary>
        public static string plhPhone {
            get {
                return ResourceManager.GetString("plhPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การเดินทางครั้งนี้ไม่ได้อยู่ กรุณาค้นหาสำหรับทัวร์อื่น.
        /// </summary>
        public static string SearchTourNotFound {
            get {
                return ResourceManager.GetString("SearchTourNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ส่งรายชื่อผู้ติดต่อที่ล้มเหลว โปรดส่งใบสมัคร.
        /// </summary>
        public static string sendContactError {
            get {
                return ResourceManager.GetString("sendContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณส่งให้ประสบความสำเร็จในการติดต่อ เราจะตอบสนองได้อย่างรวดเร็วที่สุด.
        /// </summary>
        public static string sendContactSuccess {
            get {
                return ResourceManager.GetString("sendContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษาไทย.
        /// </summary>
        public static string ThaiLan {
            get {
                return ResourceManager.GetString("ThaiLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to แนะนำ.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการทัวร์.
        /// </summary>
        public static string TitleCategoryTour {
            get {
                return ResourceManager.GetString("TitleCategoryTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติดต่อเรา.
        /// </summary>
        public static string TitleContact {
            get {
                return ResourceManager.GetString("TitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทัวร์เด่น.
        /// </summary>
        public static string titleFeaturesTour {
            get {
                return ResourceManager.GetString("titleFeaturesTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายการท่องเที่ยวเวียดนาม.
        /// </summary>
        public static string titleHeadAbout {
            get {
                return ResourceManager.GetString("titleHeadAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to หน้าหลัก.
        /// </summary>
        public static string titleHome {
            get {
                return ResourceManager.GetString("titleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การท่องเที่ยวไม่ประสบความสำเร็จ.
        /// </summary>
        public static string titleOrderFailed {
            get {
                return ResourceManager.GetString("titleOrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ติระกล้าสินค้า.
        /// </summary>
        public static string TitleShopCard {
            get {
                return ResourceManager.GetString("TitleShopCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to รายละเอียดทัวร์.
        /// </summary>
        public static string titleTourDetail {
            get {
                return ResourceManager.GetString("titleTourDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to การท่องเที่ยวแห่งประเทศไทย - เวียดนาม.
        /// </summary>
        public static string titleTravel {
            get {
                return ResourceManager.GetString("titleTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทัวร์์ภาคกลาง.
        /// </summary>
        public static string TourCentral {
            get {
                return ResourceManager.GetString("TourCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทัวร์ต่างประเทศ.
        /// </summary>
        public static string TourForeign {
            get {
                return ResourceManager.GetString("TourForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทัวร์ภาคเหนือ.
        /// </summary>
        public static string TourNorthern {
            get {
                return ResourceManager.GetString("TourNorthern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ทัวร์ภาคใต้.
        /// </summary>
        public static string TourSouth {
            get {
                return ResourceManager.GetString("TourSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to คุณป้อนข้อมูลที่ครบถ้วน.
        /// </summary>
        public static string vbErrorOderTour {
            get {
                return ResourceManager.GetString("vbErrorOderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ภาษาเวียดนาม.
        /// </summary>
        public static string Vietnames {
            get {
                return ResourceManager.GetString("Vietnames", resourceCulture);
            }
        }
    }
}
