//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaiVietSmileTravel.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThaiVietSmileTravel.Globalization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt tour.
        /// </summary>
        public static string btnAddShoping {
            get {
                return ResourceManager.GetString("btnAddShoping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục mua hàng.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string btnDetail {
            get {
                return ResourceManager.GetString("btnDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt tour.
        /// </summary>
        public static string btnOrderTour {
            get {
                return ResourceManager.GetString("btnOrderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật số người.
        /// </summary>
        public static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với chúng tôi.
        /// </summary>
        public static string h3Contact {
            get {
                return ResourceManager.GetString("h3Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string lblAddress {
            get {
                return ResourceManager.GetString("lblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận liên hệ từ website ThaiVietSmilTravel.
        /// </summary>
        public static string lblConfigFromEmailDisplayNameContact {
            get {
                return ResourceManager.GetString("lblConfigFromEmailDisplayNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đặt tour từ website ThaiVietSmilTravel.
        /// </summary>
        public static string lblConfigFromEmailDisplayNameOder {
            get {
                return ResourceManager.GetString("lblConfigFromEmailDisplayNameOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận đơn hàng website thaivietsmile.
        /// </summary>
        public static string lblConfigOderTour {
            get {
                return ResourceManager.GetString("lblConfigOderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có câu hỏi hoặc muốn biết thêm thông tin?.
        /// </summary>
        public static string lblContactQuestion {
            get {
                return ResourceManager.GetString("lblContactQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&quot;color:green&quot;&gt;THAIVIET SMILE TRAVEL CO., LTD.&lt;/h4&gt;
        ///                &lt;ul&gt;
        ///					&lt;Li&gt; Hãy Tour Việt Nam. Tất cả các chuyên gia Việt Nam &lt;/ li&gt;.
        ///					&lt;Li&gt; Hãy Tour. Việt Nam - Việt Nam - Trung Việt Nam &lt;/ li&gt;.
        ///					&lt;Li&gt; Task Group đạt Services Group (công ty là hài lòng để liên lạc cơ quan chức năng tại Việt Nam để được. Nếu không có chi phí) &lt;/ li&gt;.
        ///					&lt;Li&gt; Một hướng dẫn viên nói tiếng Anh và Thái Lan chăm sóc khách hàng hài hòa &lt;/ li&gt;.
        ///                    &lt;li&gt;Liên lạc với chúng tôi tại Mr.Lon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lblContentAbout {
            get {
                return ResourceManager.GetString("lblContentAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt truy cập.
        /// </summary>
        public static string lblCountVisistor {
            get {
                return ResourceManager.GetString("lblCountVisistor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cần đặt.
        /// </summary>
        public static string lblDateOrder {
            get {
                return ResourceManager.GetString("lblDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ từ khách hàng.
        /// </summary>
        public static string lblFromEmailDisplayNameContact {
            get {
                return ResourceManager.GetString("lblFromEmailDisplayNameContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt tour từ khách hàng.
        /// </summary>
        public static string lblFromEmailDisplayNameOder {
            get {
                return ResourceManager.GetString("lblFromEmailDisplayNameOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4 style=&quot;color:green&quot;&gt;THAIVIET SMILE TRAVEL CO., LTD.&lt;/h4&gt;
        ///                &lt;ul&gt;
        ///                    &lt;li&gt;Liên lạc với chúng tôi tại Mr.Long Thái Lan Tel 0876366396 - 00 984 916 745 457 Việt Nam.&lt;/li&gt;
        ///                    &lt;li&gt;E-mail : thaivietsmiletravel@gmail.com&lt;/li&gt;
        ///                    &lt;li&gt;Skype : thaivietsmiletravel&lt;/li&gt;
        ///                    &lt;li&gt;ID Line : thaivietsmiletravel &lt;/li&gt;
        ///                    &lt;li style=&quot;color:green&quot;&gt;Văn phòng tại Hà Nội&lt;/li&gt;
        ///                    &lt;li&gt;268 Nguyễn Xiển, Thanh Xu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string lblHeadContact {
            get {
                return ResourceManager.GetString("lblHeadContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đặt tour.
        /// </summary>
        public static string lblHederFormOder {
            get {
                return ResourceManager.GetString("lblHederFormOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình Ảnh.
        /// </summary>
        public static string lblImage {
            get {
                return ResourceManager.GetString("lblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string lblNameCustome {
            get {
                return ResourceManager.GetString("lblNameCustome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string lblNameCustomOder {
            get {
                return ResourceManager.GetString("lblNameCustomOder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tour.
        /// </summary>
        public static string lblNameTour {
            get {
                return ResourceManager.GetString("lblNameTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đêm.
        /// </summary>
        public static string lblNight {
            get {
                return ResourceManager.GetString("lblNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có tour nào trong giỏ hàng. Bạn vui lòng chọn tour.
        /// </summary>
        public static string lblNoSelectTour {
            get {
                return ResourceManager.GetString("lblNoSelectTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string lblNote {
            get {
                return ResourceManager.GetString("lblNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý: các bạn đặt tour không cần phải thanh toán online. Bên mình sẽ liên hệ với bạn sau khi thỏa thuận xong thì mới tiến hành thanh toán trực tiếp.
        /// </summary>
        public static string lblNoteOrderTour {
            get {
                return ResourceManager.GetString("lblNoteOrderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số người.
        /// </summary>
        public static string lblNumberCustom {
            get {
                return ResourceManager.GetString("lblNumberCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tour.
        /// </summary>
        public static string lblNumberTour {
            get {
                return ResourceManager.GetString("lblNumberTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string lblPhone {
            get {
                return ResourceManager.GetString("lblPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn hàng mới từ website thaivietsmile.
        /// </summary>
        public static string lblSubOderTour {
            get {
                return ResourceManager.GetString("lblSubOderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string lblSumPrice {
            get {
                return ResourceManager.GetString("lblSumPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy điền vào form dưới đây và gửi về chúng tôi, chúng tôi sẽ phản hồi sớm nhất có thể.
        /// </summary>
        public static string lblTitleInputFormContact {
            get {
                return ResourceManager.GetString("lblTitleInputFormContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tour.
        /// </summary>
        public static string lblTour {
            get {
                return ResourceManager.GetString("lblTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chi tiết.
        /// </summary>
        public static string lblTourDetail {
            get {
                return ResourceManager.GetString("lblTourDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string lblUnitPrice {
            get {
                return ResourceManager.GetString("lblUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã đặt tour thành công. Chúng tôi sẽ liên hệ ngay với bạn..
        /// </summary>
        public static string oderTourSuccess {
            get {
                return ResourceManager.GetString("oderTourSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt tour không thành công. Xin vui lòng đặt lại..
        /// </summary>
        public static string orderTourError {
            get {
                return ResourceManager.GetString("orderTourError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ.
        /// </summary>
        public static string plhAddress {
            get {
                return ResourceManager.GetString("plhAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string plhDateOrder {
            get {
                return ResourceManager.GetString("plhDateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập Email.
        /// </summary>
        public static string plhEmail {
            get {
                return ResourceManager.GetString("plhEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ.
        /// </summary>
        public static string plhEnterAdress {
            get {
                return ResourceManager.GetString("plhEnterAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên công ty.
        /// </summary>
        public static string plhEnterCompany {
            get {
                return ResourceManager.GetString("plhEnterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email.
        /// </summary>
        public static string plhEnterEmail {
            get {
                return ResourceManager.GetString("plhEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ.
        /// </summary>
        public static string plhEnterFirtName {
            get {
                return ResourceManager.GetString("plhEnterFirtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên.
        /// </summary>
        public static string plhEnterLastName {
            get {
                return ResourceManager.GetString("plhEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ghi chú.
        /// </summary>
        public static string plhEnterMesseage {
            get {
                return ResourceManager.GetString("plhEnterMesseage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại liên hệ.
        /// </summary>
        public static string plhEnterPhone {
            get {
                return ResourceManager.GetString("plhEnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập đầy đủ họ và tên.
        /// </summary>
        public static string plhNameCustome {
            get {
                return ResourceManager.GetString("plhNameCustome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng ghi chú nếu có.
        /// </summary>
        public static string plhNote {
            get {
                return ResourceManager.GetString("plhNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại.
        /// </summary>
        public static string plhPhone {
            get {
                return ResourceManager.GetString("plhPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi liên hệ không thành công. Vui lòng gửi lại.
        /// </summary>
        public static string sendContactError {
            get {
                return ResourceManager.GetString("sendContactError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi liên hệ thành công. Chúng tôi sẽ hồi đáp nhanh nhất có thể.
        /// </summary>
        public static string sendContactSuccess {
            get {
                return ResourceManager.GetString("sendContactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng thái.
        /// </summary>
        public static string ThaiLan {
            get {
                return ResourceManager.GetString("ThaiLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIỚI THIỆU.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tour.
        /// </summary>
        public static string TitleCategoryTour {
            get {
                return ResourceManager.GetString("TitleCategoryTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        public static string TitleContact {
            get {
                return ResourceManager.GetString("TitleContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Đặc Sắc.
        /// </summary>
        public static string titleFeaturesTour {
            get {
                return ResourceManager.GetString("titleFeaturesTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du lịch Việt Nam.
        /// </summary>
        public static string titleHeadAbout {
            get {
                return ResourceManager.GetString("titleHeadAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string titleHome {
            get {
                return ResourceManager.GetString("titleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giỏ hàng.
        /// </summary>
        public static string TitleShopCard {
            get {
                return ResourceManager.GetString("TitleShopCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Miền Trung.
        /// </summary>
        public static string TourCentral {
            get {
                return ResourceManager.GetString("TourCentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Nước Ngoài.
        /// </summary>
        public static string TourForeign {
            get {
                return ResourceManager.GetString("TourForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Miền Bắc.
        /// </summary>
        public static string TourNorthern {
            get {
                return ResourceManager.GetString("TourNorthern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Miền Nam.
        /// </summary>
        public static string TourSouth {
            get {
                return ResourceManager.GetString("TourSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng nhập đầy đủ thông tin.
        /// </summary>
        public static string vbErrorOderTour {
            get {
                return ResourceManager.GetString("vbErrorOderTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        public static string Vietnames {
            get {
                return ResourceManager.GetString("Vietnames", resourceCulture);
            }
        }
    }
}
